---
- name: disable any repos specified
  sudo: yes
  shell: yum-config-manager --disable {{ item }}
  with_items: test_cfg.setup.disable_repos
  when:
      test_cfg.setup | default(false) and test_cfg.setup.disable_repos | default(false)

- name: enable any additional repos to be used
  sudo: yes
  shell: yum-config-manager --enable {{ item }}
  with_items: test_cfg.setup.enable_repos
  when:
      test_cfg.setup | default(false) and test_cfg.setup.enable_repos | default(false)

- name: grab short reposlist
  shell: yum repolist all

- name: install test dependencies rpm needed to run test
  sudo: yes
  yum: pkg={{ item }} state=latest
  with_items: test_cfg.setup.install
  when:
    test_cfg.setup | default(false) and test_cfg.setup.install | default(false)

- name: remove unwanted rpms specified in test dependencies
  sudo: yes
  yum: pkg={{ item }} state=absent
  with_items: test_cfg.setup.remove
  when:
    test_cfg.setup | default(false) and test_cfg.setup.remove | default(false)

- name: install packages to convert tests results into junitxml format
  sudo: yes
  yum: name={{ item }} state=present
  with_items:
      - subunit-filters
      - python-junitxml
