---
- name: compute the directory basename
  set_fact: component_basename={{ tests_path.split('/')|last }}

- name: find the test dependencies file used for the test-run
  set_fact: test_deps_file="{{ tests_path + '/' + tester.component.config_file }}" #"

- name: load config
  include_vars: "{{ test_deps_file }}"
  register: result

  #TODO(abregman): add major and minor version in distro settings
- name: set major release
  set_fact: major_release="{{ ansible_distribution + '-' + ansible_distribution_version.split('.')[0] }}"

- name: set full release
  set_fact: full_release="{{ ansible_distribution + '-' + ansible_distribution_version }}"

- name: Set test_env
  set_fact: test_env="{{ test_config.virt[item]|default(omit) }}"
  with_items:
      - "{{ major_release }}"
      - "{{ full_release }}"

- name: rsync tests dir to tester
  synchronize: src="{{ tests_path }}" dest="{{ ansible_env.HOME }}/" #"
  register: result

- name: print result
  debug: var=result

- name: Install release tool on machines
  sudo: yes
  command: "yum localinstall -y {{ product.rpm }}"

- name: Execute rhos-release for packstack poodle/puddle
  sudo: yes
  command: "rhos-release {{ product.version.major }} {{ product.repo.rhos_release.extra_args|join(' ') }}"

- name: Print component tests path
  debug: var=tests_path

- name: print HOME dir
  debug: var=ansible_env.HOME

- name: print test environment name
  debug: var=test.env_name

- name: clean log dir
  file: path={{ ansible_env.HOME }}/logs/ state=absent

- name: create log dir
  file: path={{ ansible_env.HOME }}/logs/ state=directory

- name: compute the tester path
  set_fact: component_path={{ ansible_env.HOME + '/' + component_basename }}

- name: print component path
  debug: var={{ component_path }}

- name: print test configuration
  debug: var=test_env
  register: env
