---
- name: cinder | set config vars
  set_fact: config_items = nodes.controller.storage_volume.config.cinder[product.version|string]
  when: nodes.controller.storage_volume.config.cinder is defined

- name: cinder | service | is configured
  sudo: yes
  template: src=config.j2 dest={{ cinder_conf_temp }}
  when: nodes.controller.storage_volume.config.cinder is defined

- name: cinder | crudini | merge config files
  sudo: yes
  shell: crudini --merge {{ cinder_conf }} < {{ cinder_conf_temp }}
  when: nodes.controller.storage_volume.config.cinder is defined


- name: cinder | service | EMC configured
  sudo: yes
  template: src=emc_iscsi.xml.j2 dest={{ cinder_emc_conf }}
  when: nodes.controller.storage_volume.config.cinder.emc is defined
