---

- name: glance | set config vars
  set_fact: config_items = storage.image.config.glance[product.version|string]
  when: storage.volume.config.glance is defined

- name: glance | service | is configured
  sudo: yes
  template: src=config.j2 dest={{ glance_conf_temp }}
  when: storage.image.config.glance is defined

- name: glance | crudini | merge config files
  sudo: yes
  shell: crudini --merge {{ glance_conf }} < {{ glance_conf_temp }}
  when: storage.image.config.glance is defined

- name: nova | set config vars
  set_fact: config_items = storage.image.config.nova[product.version|string]
  when: storage.volume.config.nova is defined

- name: nova | service | is configured
  sudo: yes
  template: src=config.j2 dest={{ nova_conf_temp }}
  when: storage.image.config.nova is defined

- name: nova | crudini | merge config files
  sudo: yes
  shell: crudini --merge {{ nova_conf }} < {{ nova_conf_temp }}
  when: storage.image.config.nova is defined

- name: cinder | set config vars
  set_fact: config_items = storage.image.config.cinder[product.version|string]
  when: storage.volume.config.cinder is defined

- name: cinder | service | is configured
  sudo: yes
  template: src=config.j2 dest={{ cinder_conf_temp }}
  when: storage.image.config.cinder is defined

- name: cinder | crudini | merge config files
  sudo: yes
  shell: crudini --merge {{ cinder_conf }} < {{ cinder_conf_temp }}
  when: storage.image.config.cinder is defined

