---
- include: "{{base_dir}}/khaleesi/playbooks/provisioner/manual/main.yml"
- name: clean up rdo-manager virthost
  hosts: virthost
  vars:
      - ansible_user: root
  roles:
      - { role: cleanup_nodes/rdo-manager,
          when: (installer.type == "rdo-manager" and provisioner.type == "manual")
        }
