---
- name: Install Rally dependencies on the machine
  hosts: tester
  sudo: yes
  tasks:
    - name: Install needed packages on machine
      yum: name={{ item }} state=present
      with_items:
        - git
        - which

- name: Install Rally on the machine
  hosts: tester
  sudo: yes
  tasks:
    - name: Clone Rally from git repo
      git: repo={{ rally.git.repo }} version={{ rally.git.revision }}
           dest={{ rally.dir }}

      # This URL should be in the config file (khaleesi settings)
    - name: Download cirros image
      get_url: url=http://download.cirros-cloud.net/0.3.1/cirros-0.3.1-x86_64-disk.img dest={{ rally.dir }}/etc/{{ rally.cirros_image_file }} mode=0440

    - name: Run Rally installation script
      shell: "{{ rally.dir }}/install_rally.sh -v"
      args:
        creates: "{{ rally.path }}/rally"

- name: Create keystonerc - FIXME - why to do this, esp. here?
  hosts: controller
  tasks:
    - name: Create keystonerc_admin
      template: src=../templates/keystonerc_admin.j2 dest=/root/keystonerc_admin
      sudo: yes

    - name: Create nano falvor
      shell: "source /root/keystonerc_admin && nova flavor-create m1.nano 42 64 0 1"
      sudo: yes
      # ignore errors if flavor already created
      ignore_errors: True

    - name: Create Glance Image
      glance_image:
        login_username: admin
        login_password: "{{ hostvars[nodes.controller.name].admin_password | default('redhat') }}"
        login_tenant_name: admin
        name: cirros-0.3.3-x86_64-uec
#        disk_format: ami
        state: present
        copy_from: http://download.cirros-cloud.net/0.3.3/cirros-0.3.3-x86_64-disk.img
