---
- name: Reboot machines
  shell: shutdown -r +1 && exit
  async: 0
  poll: 0
  ignore_errors: true

- name: Wait for SSH
  local_action:
      module: wait_for
          delay=60
          host={{ hostvars[inventory_hostname].ansible_ssh_host }}
          port=22
          state=started
          timeout=300
  sudo: no
  register: wait_for_ssh

- name: Fail if any machine fail
  fail: msg="Could not contact one of the nodes"
  when: wait_for_ssh|failed