---
- name: Reboot machines
  shell: shutdown -r now
  async: 100
  poll: 10
  ignore_errors: true

- name: Wait for SSH
  local_action:
      module: wait_for
          host={{ hostvars[inventory_hostname].ansible_ssh_host }}
          port=22
          state=started
  sudo: no
  register: wait_for_ssh

- name: Fail if any machine fail
  fail: msg="Could not contact one of the nodes"
  when: wait_for_ssh|failed