---
# to include this in your tasks,
# do register 'reboot_reason' via the task
# which does cause the need for restart
# (so we don't reboot unless the config changes for ex.)
- name: Reboot machines
  when: reboot_reason|changed
  shell: echo "$(( $(date +%s) - $(cat /proc/uptime | sed s/\\..*//) ))"; nohup bash -c 'sleep 1; shutdown -r now' > /root/reboot.log & exit 0
  sudo: yes
  ignore_errors: true
  register: boottime_before_reboot

- name: Wait for reboot and SSH
  when: reboot_reason|changed
  sudo: no
  local_action:
    module: shell OLDBOOTTIME={{ boottime_before_reboot.stdout }} {{ working_dir }}/tools/wait_for_ssh.sh -v {{ hostvars[inventory_hostname].ansible_ssh_host }} -o User={{ hostvars[inventory_hostname].ansible_ssh_user }} -i {{ provisioner.key_file }}

