---
- name: Update packages on the host
  hosts: undercloud
  vars:
      - ansible_user: root
  tasks:
      - name: repolist
        command: yum -d 7 repolist

      - name: update all packages
        yum: name=* state=latest

