---
- name: install the undercloud
  hosts: undercloud
  tasks:
    - name: update hosts file for localhost.localhost (workaround for puppet, discovered on centos7)
      lineinfile: dest=/etc/hosts line="127.0.0.1   localhost localhost.localhost"
      sudo: yes

    - name: install the undercloud
      shell: openstack undercloud install --debug &> {{ instack_user_home }}/undercloud_install_initial_install.log
      ignore_errors: yes
      register: uc_status

    - name: get overview about what went wrong in undercloud installation
      shell: |
           tail -n 200 {{ instack_user_home }}/undercloud_install_initial_install.log
      ignore_errors: yes
      when: uc_status.rc != 0

    - name: check if undercloud failed
      fail: msg="Undercloud install failed"
      when: uc_status.rc != 0

    - name: copy files to home
      sudo: yes
      command: cp /root/{{ item }} {{ instack_user_home }}/{{ item }}
      with_items:
        - tripleo-undercloud-passwords
        - stackrc

    - name: chown files for stack user
      sudo: yes
      command: chown stack:stack {{ instack_user_home }}/{{ item }}
      with_items:
        - tripleo-undercloud-passwords
        - stackrc

- name: confirm installing the undercloud is idempotent
  hosts: undercloud
  tasks:
    - name: install the undercloud
      shell: openstack undercloud install &> {{ instack_user_home }}/undercloud_install_idempotent_check.log
      ignore_errors: yes
      register: uc_idemp_status

    - name: get overview about what went wrong in idempotent undercloud installation
      shell: |
           tail -n 200 {{ instack_user_home }}/undercloud_install_idempotent_check.log
      ignore_errors: yes
      when: uc_idemp_status.rc != 0

    - name: check if idempotent undercloud installation failed
      fail: msg="Undercloud install failed"
      when: uc_idemp_status.rc != 0
