- name: Group hosts by post action - update
  hosts: undercloud:overcloud
  gather_facts: no
  tasks:
    - group_by: key="update"
      when: installer.updates is defined and
            installer.updates.enabled|bool

- name: Fetch updates files
  hosts: update:!overcloud
  tasks:
    - name: fetch 55-heat-config script BZ 1278181
      fetch:
        src: "/usr/share/openstack-heat-templates/software-config/elements/heat-config/os-refresh-config/configure.d/55-heat-config"
        dest: "{{ lookup('env', 'PWD') }}/55-heat-config"
        flat: yes
      when: workaround.rhbz1278181.enabled|bool

    - name: fetch heat-config-rebuild-deployed script BZ 1278181
      fetch:
        src: "/usr/share/openstack-heat-templates/software-config/elements/heat-config/bin/heat-config-rebuild-deployed"
        dest: "{{ lookup('env', 'PWD') }}/heat-config-rebuild-deployed"
        flat: yes
      when: workaround.rhbz1278181.enabled|bool

- name: Dump packages list
  hosts: update:!undercloud
  tasks:
    - name: dump package list
      shell: rpm -qa &> {{ ansible_host }}-rpm.log

    - name: copy 55-heat-config file to node BZ 1278181
      sudo: yes
      copy:
        src: "{{ lookup('env', 'PWD') }}/55-heat-config"
        dest: "/usr/libexec/os-refresh-config/configure.d/55-heat-config"
        mode: 0755
      when: workaround.rhbz1278181.enabled|bool

    - name: copy file to node BZ 1278181
      sudo: yes
      copy:
        src: "{{ lookup('env', 'PWD') }}/heat-config-rebuild-deployed"
        dest: "/home/heat-admin/heat-config-rebuild-deployed"
        mode: 0755
      when: workaround.rhbz1278181.enabled|bool

    - name: copy and make heat-config rebuild executable
      shell: >
        sudo mkdir -p /usr/share/openstack-heat-templates/software-config/elements/heat-config/bin;
        sudo cp /home/heat-admin/heat-config-rebuild-deployed  \
        /usr/share/openstack-heat-templates/software-config/elements/heat-config/bin/heat-config-rebuild-deployed;
        sudo chmod +x  /usr/share/openstack-heat-templates/software-config/elements/heat-config/bin/heat-config-rebuild-deployed;
        sudo /usr/share/openstack-heat-templates/software-config/elements/heat-config/bin/heat-config-rebuild-deployed

- name: Update the Overcloud
  hosts: update:!overcloud
  tasks:
    - name: get plan list
      register: overcloud_uuid_result
      shell: >
          source {{ instack_user_home }}/stackrc;
          openstack management plan list | grep overcloud | cut -d " " -f2
      when: installer.deploy.type == 'plan'

    - name: set fact for openstack management plan
      set_fact:
        overcloud_uuid: "{{ overcloud_uuid_result.stdout }}"
      when: installer.deploy.type == 'plan'

    - name: copy template file for update overcloud workaround BZ 1272347
      template:
        src=templates/upgrade.yml.j2
        dest={{ instack_user_home }}/upgrade.yml
        mode=0755
      when: workaround.rhbz1272347.enabled|bool

    - name: copy template file for update overcloud
      template:
        src=templates/update-overcloudrc.j2
        dest={{ instack_user_home }}/update-overcloudrc
        mode=0755

    - name: echo update command
      register: overcloud_update_command
      shell: >
          source {{ instack_user_home }}/stackrc;
          source {{ instack_user_home }}/update-overcloudrc;
          echo $UPDATE_COMMAND

    - name: update-overcloud
      register: update
      ignore_errors: yes
      shell: >
          source {{ instack_user_home }}/stackrc;
          {{ overcloud_update_command.stdout }} &> update_overcloud_console.log

    - name: get neutron debug info after updates
      register: neutron_port_list_output
      shell: >
          source {{ instack_user_home }}/stackrc;
          neutron port-list;

    - name: get openstack-tripleo-heat-template version after updates
      register: openstack-tripleo-heat-template_version
      shell: >
          rpm -qa | grep openstack-tripleo-heat-template

    - name: heat stack-list
      register: update_status
      ignore_errors: yes
      shell: >
          source {{ instack_user_home }}/stackrc;
          heat stack-list | grep 'UPDATE_COMPLETE'

    - name: fail when status is not COMPLETE
      fail: msg="Overcloud update failed"
      when: update_status.rc != 0

- name: Check update status
  hosts: update:!undercloud
  tasks:
    - name: dump package list
      shell: rpm -qa &> {{ ansible_host }}-rpm-updated.log

    - name: get rpm list stat
      register: rpm_list_result
      stat: path=~/{{ ansible_host }}-rpm.log

    - name: get rpm updated stat
      register: rpm_list_updated_result
      stat: path=~/{{ ansible_host }}-rpm-updated.log

    - name: fail when rpm list checksum are equal
      fail: msg="Failed, no package has been updated..."
      when: rpm_list_result.stat.checksum == rpm_list_updated_result.stat.checksum
