---
- name: Set path for tests
  hosts: controller
  gather_facts: yes
  tasks:
      - name: Set tests path
        set_fact: tests_path="{{ tester.component.dir }}"

- name: Run pre tasks
  hosts: controller
  gather_facts: yes
  roles:
    - component-test/pre

- name: Configure Tempest
  hosts: controller
  vars:
      controller_auth_url: "http://127.0.0.1:5000/v2.0"
      admin_password: "{{ hostvars[provisioner.nodes.controller.name].admin_password | default('redhat') }}"
  roles:
      - openstack/create_users
  tasks:
      - name: Ensure tempest configuration directory exists
        sudo: yes
        file: path={{ tester.component.conf_dir | default('/opt/stack/tempest/etc') }} state=directory mode=0777

      - name: Deploy tempet.conf
        sudo: yes
        template: src=templates/tempest_conf.j2 dest=/opt/stack/tempest/etc/tempest.conf mode=0666

      - name: Set public_network_id
        sudo: yes
        environment:
            OS_USERNAME: admin
            OS_PASSWORD: "{{ admin_password }}"
            OS_TENANT_NAME: admin
            OS_AUTH_URL: "{{ controller_auth_url }}"
        shell: >
            echo "public_network_id = $(neutron net-list | grep public | awk '{print $2}')" >> {{ tester.component.conf_dir | default('/opt/stack/tempest/etc') }}/tempest.conf;

      - name: Set tempest api environment
        shell: >
            echo "export OS_USERNAME={{ tester.accounts[0].username }}" >> ~/.bash_profile;
            echo "export OS_PASSWORD={{ tester.accounts[0].password }}" >> ~/.bash_profile;
            echo "export OS_TENANT_NAME={{ tester.accounts[0].tenant_name }}" >> ~/.bash_profile;
            echo "export OS_AUTH_URL={{ controller_auth_url }}" >> ~/.bash_profile
