---
- name: Run horizon integration tests
  hosts: tester
  gather_facts: yes
  sudo: no
  tasks:
      - name: run integration tests
        environment:
          INTEGRATION_TESTS: 1
          GRID_HUB: 'http://127.0.0.1:4444/wd/hub'
          BROWSER_NAME: "{{ lookup('env', 'BROWSER_NAME') }}"
          BROWSER_VERSION: "{{ lookup('env', 'BROWSER_VERSION') }}"
          BROWSER_PLATFORM: "{{ lookup('env', 'BROWSER_PLATFORM') }}"
        shell: |
             [ -d ~/{{ tester.venv_dir }} ] && source ~/{{ tester.venv_dir }}/bin/activate
             nosetests -v -a "{{ tester.integration.tests_tag }}" --with-xunit --xunit-file=horizon.xml openstack_dashboard/test/integration_tests/tests chdir=~/{{ tester.dir }}
        ignore_errors: true
        async: 21600
        poll: 30