---
# setup packstack prerequisites
- name: Setup openstack repos
  hosts: openstack_nodes
  gather_facts: yes
  sudo: yes
  tasks:
      - name: Disable any existing repos
        shell: sed -i 's/enabled=1/enabled=0/' /etc/yum.repos.d/*
        register: shell_result
        changed_when: "shell_result.rc == 0"
        failed_when: "shell_result.rc > 2"

      - name: Install release tool on machines
        command: "yum localinstall -y {{ product.rpm }}"

      - name: Get RHOS repo files
        rhos-release:
            release: "{{ product.version.major }}"
            repo_type: "{{ product.repo.type }}"
            state: "{{ product.repo.state }}"
            distro: "{{ product.repo.distro | default(omit) }}"
            dest: "{{ product.repo.dest | default(omit) }}"

      - name: repolist
        command: yum -d 7 repolist

- name: Get build details
  hosts: controller
  sudo: no
  roles:
    - build_mark/build
