---
- name: Install, configure and start Sahara service
  hosts: controller:&sahara
  vars_files:
    - ../vars/sahara-defaults.yml
  tasks:
    - include: service.yml
  tags:
    - sahara

- name: Install and configure Sahara Dashboard
  hosts: controller:&sahara
  vars_files:
    - ../vars/sahara-defaults.yml
  sudo: yes
  tasks:
    - include: dashboard.yml
      when: (product.name == "rhos" and product.version|string == "5.0")
             or (product.name == "rdo" and product.version|string == "icehouse")
  tags:
    - sahara

