---
- name: Wait for openstack port 35357 to open
  sudo: no
  delegate_to: localhost
  wait_for_ssh:
      host: "{{ hostvars[inventory_hostname].ansible_host }}"
      port: 35357
      delay: 10
      timeout: 120
  register: wait_for_openstack

- name: Fail if any of them fail
  fail: msg="Could not find any service running on port 35357"
  when: wait_for_openstack|failed

- name: Status
  shell: source /root/keystonerc_admin; openstack-status
  register: openstack_status
  ignore_errors: yes

- debug: var=openstack_status.stdout_lines

- name: Check if openstack-status reports dead services
  shell: >
    sed -n '/== Keystone users ==/q;p' <<<'{{ openstack_status.stdout }}' | grep -v '==' | grep -v "(disabled on boot)" | grep dead
  register: dead_services
  failed_when: dead_services.rc >= 2

- name: Get names of failed services, if any
  shell: >
    tr -d [[:blank:]] <<<'{{ dead_services.stdout }}' | awk -F: '{print $1}'
  register: dead_services_names
  when: dead_services.stdout != ""

- name: Names of failed services
  debug: var=dead_services_names.stdout_lines
  when: dead_services.stdout != ""

# This is falsely reporting that swift is dead, going to leave this as a warning until we've figured out the issue
#- name: Fail playbook in case of dead services
# fail: msg=" There are dead services"
# when: dead_services.stdout != ""
