---
- name: Acquire nodes
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Get nodes
      centosci:
           request="get"
           url="{{ provisioner.url }}"
           ver="{{ provisioner.distro.version }}"
           arch="{{ provisioner.arch }}"
           count="1"
           ram_gb="{{ provisioner.ram_gb |default(1) }}"
      with_dict: provisioner.nodes
      register: provisioned_nodes
      until: provisioned_nodes|success
      retries: 5
      delay: 120

    - name: Save SSID to file
      shell: >
          echo "{{ provisioned_nodes.results.0.ssid }}" > {{ lookup('env', 'PWD') }}/centosci_ssid_{{provisioned_nodes.results.0.ssid}}
      with_dict: provisioner.nodes

    - name: Add created hosts to host list
      add_host:
        name="{{ item.hosts.0.name }}"
        groups="{{ item.item.value.groups
            if item.item.value.groups is string
            else item.item.value.groups| join(',') }}"
        ansible_fqdn="{{ item.hosts.0.hostname }}"
        ansible_user="{{ provisioner.remote_user }}"
        ansible_ssh_private_key_file="{{ provisioner.key_file }}"
        ansible_host="{{ item.hosts.0.hostname }}"
      with_items: provisioned_nodes.results

- name: wait for hosts to get reachable
  hosts: provisioned
  gather_facts: no
  max_fail_percentage: 0
  tasks:
      delegate_to: localhost
      wait_for_ssh:
          host: "{{ hostvars[inventory_hostname].ansible_host }}"
          user: root
          key: "{{ hostvars[inventory_hostname].ansible_ssh_private_key_file }}"
  sudo: no
