---
- name: Install release tool
  sudo: yes
  command: "yum localinstall -y {{ product.rpm }}"
  when: product.rpm is defined and product.rpm

- name: Execute rhos-release for packstack poodle/puddle
  sudo: yes
  command: "rhos-release {{ product.full_version|int }} {{ product.repo.rhos_release.extra_args|join(' ') }}"
  when: product.rpm is defined and product.rpm

- name: Unpack the repo
  unarchive:
    src: "{{ base_dir }}/delorean_rpms.tar.gz"
    dest: "{{ ansible_env.HOME }}"

- name: Lower repo priorities from one
  sudo: yes
  shell: >
    for file in /etc/yum.repos.d/*.repo; do
        sed -i 's/priority=1/priority=2/' $file;
    done

- name: Setup repository configuration
  sudo: yes
  template:
    src: "{{ base_dir }}/khaleesi/roles/delorean/templates/delorean_rpms.j2"
    dest: "/etc/yum.repos.d/delorean_rpms.repo"

- name: print out current repo config
  sudo: yes
  command: yum -d 7 repolist
