---
- name: Fetch results
  hosts: tester
  gather_facts: no
  tasks:
    -  fetch: src={{ tempest.dir }}/tempest.xml
              dest={{ lookup('env', 'PWD') }}/nosetests.xml
              flat=yes
