---
- name: Install tempest from rpm
  hosts: tester
  sudo: yes
  tasks:
    - template: dest=/etc/yum.repos.d/tempest.repo src=../templates/tempest-master.repo owner=root group=root mode=0644
      register: tempest_repo
      when: tempest.rpm.release == 'master'

    - command: yum clean all
      when: tempest_repo|changed

    # TODO: if release != master use rdo/rhos release rpm/tool
    - yum: name=openstack-tempest-{{ tempest.rpm.release }} state=present
      register: tempest_rpm

    - command: rpm -q --qf %{VERSION}-%{RELEASE} openstack-tempest-{{ tempest.rpm.release }}
      register: tempest_rpm_version

    - debug: "msg='Build mark: tempest={{ tempest_rpm_version.stdout }}'"
