---
- include: pre-{{ tempest.setup_method|replace("tempest/", "") }}.yml

- name: Configure tempest
  hosts: tester
  sudo: yes 
  tasks:
    # FIXME: use non-root user (and HOME path) for configure-tempest.sh,
    #        after tempest.rpm ships and reads /etc/tempest or ~/tempest.conf (or something in that style) 
    - template: dest=/root/configure-tempest.sh src=../templates/configure-tempest.sh owner=root group=root mode=0755
      register: config_script
    - command: /root/configure-tempest.sh
      when: config_script|changed
    - name: initiate testr
      shell: creates="{{ tempest.dir }}/.testrepository" chdir="{{ tempest.dir }}" testr init

