---
- name: Create keystonerc
  hosts:
      - tester
      - controller
  sudo: yes
  tasks:
      - name: Create keystonerc_admin
        template: src=../templates/keystonerc_admin.j2 dest=/root/keystonerc_admin

- name: Run tempest
  hosts: tester
  gather_facts: no
  tasks:
      - name: generate tempest.conf
        shell: chdir="{{ tempest.dir }}" python {{ tempest.dir }}/tools/config_tempest.py --out {{ tempest.dir }}/etc/tempest.conf --debug  --create identity.uri http://{{ hostvars[nodes.controller.name].ansible_default_ipv4.address }}:5000/v2.0/ compute.allow_tenant_isolation true object-storage.operator_role SwiftOperator identity.admin_password {{ hostvars[nodes.controller.name].admin_password|default('redhat') }} identity.password {{ hostvars[nodes.controller.name].demo_password|default('secrete') }}

      - name: initiate testr
        shell: chdir="{{ tempest.dir }}" testr init

      - name: run tempest
        shell: chdir="{{ tempest.dir }}" {{ tempest.dir }}/tools/run-tests.sh tempest
        ignore_errors: True
