---
- name: Create keystonerc - FIXME - why to do this, esp. here?
  hosts:
      - tester
      - controller
  sudo: yes
  tasks:
      - name: Create keystonerc_admin
        template: src=../templates/keystonerc_admin.j2 dest=/root/keystonerc_admin

- name: Run tempest
  hosts: tester
  gather_facts: no
  sudo: yes # FIXME: drop sudo after tempest.rpm support it (no writing into /usr/share needed)
  tasks:
      - name: run tempest
        shell: chdir="{{ tempest.dir }}" {{ tempest.dir }}/tools/run-tests.sh tempest
        ignore_errors: True
