---
- name: Create keystonerc
  hosts:
      - tempest
      - controller
  sudo: yes
  tasks:
      - name: Create keystonerc_admin
        template: src=../templates/keystonerc_admin.j2 dest=/root/keystonerc_admin

- name: Create external network
  hosts: controller
  sudo: yes
  tasks:
      # THIS NEEDS TO BE CHANGED - Network params should be in the config
      - name: Create external network - neutron
        neutron_network:
            login_username: admin
            login_password: "{{ hostvars[nodes.controller.name].admin_password | default('redhat') }}"
            login_tenant_name: admin
            name: external
            state: present
            provider_network_type: flat
            provider_physical_network: myphysnet
            router_external: yes
            shared: yes
            admin_state_up: yes
        when: installer.network.plugin.name == neutron

- name: Create tempest config file
  hosts: tempest
  vars:
      tempest_config_generate_command: >
      python {{ tempest.dir }}/tools/config_tempest.py --out {{ tempest.dir }}/etc/tempest.conf
            --debug  --create
            identity.uri http://{{ hostvars[nodes.controller.name].ansible_default_ipv4.address }}:5000/v2.0/
            compute.allow_tenant_isolation true
            object-storage.operator_role SwiftOperator
            identity.admin_password "{{ hostvars[nodes.controller.name].admin_password | default('redhat') }}"
            identity.password "{{ hostvars[nodes.controller.name].demo_password | default('secrete') }}"

