---
# provison
- include: provision/{{ provisioner.type }}.yml

# deploy openstack
- include: installer/{{ installer.name }}/pre.yml
- include: installer/{{ installer.name }}/run.yml
- include: installer/{{ installer.name }}/post.yml

# deploy testing environment
- include: tester/{{ tester.name }}/pre.yml
- include: tester/{{ tester.name }}/run.yml
- include: tester/{{ tester.name }}/post.yml

# run tests