---
# provison
- include: provisioner/{{ provisioner.type }}/main.yml

# deploy openstack
- include: installer/{{ installer.name }}/pre.yml
- include: installer/{{ installer.name }}/run.yml
- include: installer/{{ installer.name }}/post.yml

# deploy ad-hoc modules
- include: adhoc/sahara/main.yml

# deploy testing environment
- include: tester/{{ tester.name }}/pre.yml
- include: tester/{{ tester.name }}/run.yml
- include: tester/{{ tester.name }}/post.yml

# collect logs
- include: collect_logs.yml

# clean up
- include: provisioner/{{ provisioner.type }}/cleanup.yml
