---
- name: Install, configure and start Sahara service
  hosts: controller:&sahara
  roles:
    - { role: openstack/sahara }
  tags:
    - sahara

- name: Install and configure Sahara Dashboard
  hosts: controller:&sahara
  sudo: yes
  roles:
    - { role: openstack/sahara/dashboard,
        when: (product.name == "rhos" and product.version|string == "5.0")
              or (product.name == "rdo" and product.version|string == "icehouse")
      }
  tags:
    - sahara

