---
- name: Install configure and start volume storage service
  hosts: controller:&storage_volume
  roles:
    - { role: adhoc/storage/volume }
  tags:
    - volume

- name: Install configure and start image storage service
  hosts: controller:&storage_image
  roles:
    - { role: adhoc/storage/image}
  tags:
    - image

- name: Install configure and start object storage service
  hosts: controller:&storage_object
  roles:
    - { role: adhoc/storage/object }
  tags:
    - object

