---
- name: Post deploy
  hosts: undercloud
  tasks:
    - name: set fact overcloud_deployment_result
      set_fact:
          overcloud_deployment_result: "{{ overcloud_deployment_result | default('1') }}"

    - name: echo deploy-overcloud return code in status playbook
      debug: var=overcloud_deployment_result

    - name: print result of deploy-overcloud install
      debug: var=overcloud_deployment_result.stdout_lines
      when: overcloud_deployment_result is defined and overcloud_deployment_result == "0"

    - name: See the overcloud deployment
      shell: >
          source {{ instack_user_home }}/stackrc;
          heat stack-list;
          nova list;
          ironic node-list;
          openstack server list;

    - name: heat debug deploy-overcloud failure
      ignore_errors: yes
      shell: >
          source {{ instack_user_home }}/stackrc;
          heat resource-list overcloud;
          heat event-list overcloud;
      when: overcloud_deployment_result is defined and overcloud_deployment_result != "0"

    - name: debug deploy-overcloud failure
      ignore_errors: yes
      shell: >
          source {{ instack_user_home }}/stackrc;
          heat resource-show overcloud ControllerNodesPostDeployment;
      when: overcloud_deployment_result is defined and overcloud_deployment_result != "0"

    - name: debug all deployment failures
      ignore_errors: yes
      shell: >
          source {{ instack_user_home }}/stackrc;
          for failed_deployment in $(heat resource-list --nested-depth 5 overcloud | grep FAILED | grep 'StructuredDeployment ' | cut -d '|' -f3); \
          do heat deployment-show $failed_deployment; done;
      when: overcloud_deployment_result is defined and overcloud_deployment_result != "0"

    - name: grep for errors in heat-engine.log
      when: overcloud_deployment_result is defined and overcloud_deployment_result != "0"
      sudo: yes
      command: "grep ERROR /var/log/heat/heat-engine.log"
      ignore_errors: yes

    - name: grep for errors in the ironic logs
      when: overcloud_deployment_result is defined and overcloud_deployment_result != "0"
      sudo: yes
      shell: "cat /var/log/ironic/* | grep -v ERROR_FOR_DIVISION_BY_ZERO | grep ERROR"
      ignore_errors: yes

    - name: show ironic nodes create template
      template: >
          src={{ base_dir }}/khaleesi/playbooks/installer/rdo-manager/templates/show_nodes.sh
          dest={{ instack_user_home }}/show_nodes.sh
          mode=0755
      when: overcloud_deployment_result is defined and overcloud_deployment_result == "0"

    - name: show ironic nodes
      shell: "{{ instack_user_home }}/show_nodes.sh"
      when: overcloud_deployment_result is defined and overcloud_deployment_result == "0"

- name: debug output from the overcloud controller
  hosts: overcloud-controller-0
  gather_facts: no
  tasks:
    - name: ceph status
      sudo: yes
      command: ceph status
      ignore_errors: yes

- name: dump journal logs into /var/log for collection
  hosts: overcloud
  gather_facts: no
  tasks:
    - name: get overcloud puppet logs
      sudo: yes
      shell: journalctl -u os-collect-config > /var/log/os-collect-config.log
      ignore_errors: yes

    - name: get ironic logs
      sudo: yes
      shell: journalctl -u openstack-ironic-conductor -u openstack-ironic-api > /var/log/ironic-conductor-api-journal.log
      ignore_errors: yes

- name: fail playbook when instack-deploy-overcloud fails
  hosts: undercloud
  tasks:
    - fail: msg="instack-deploy-overcloud failed, see the above debug information"
      when: overcloud_deployment_result is defined and overcloud_deployment_result != "0"
